name: main
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Write Test secret
      env:
        MY_SECRET_TEST_01: ${{ secrets.MY_SECRET_TEST_01 }}
        REPO_SEC_01: ${{ secrets.REPO_SEC_01 }}
        MY_SECRET_TEST_04: ${{ secrets.MY_SECRET_TEST_04 }}
      run: |
        echo $MY_SECRET_TEST_04 | sed 's/./& /g'
