name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "Hello!" \
          echo "MY_SECRET_TEST_01 = $MY_SECRET_TEST_01" \
          echo "REPO_SEC_01 = $REPO_SEC_01" \
          echo "Goodbye..."
