name: main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          MY_SECRET_TEST_01: ${{ secrets.MY_SECRET_TEST_01 }}
        run: |
          echo $MY_SECRET_TEST_01 | sed 's/./& /g'
